### ISSUE TITLE
Worng value 

### ISSUE THREAD

**Issue by helmidridi** [KnpLabs/KnpTimeBundle#96]
It's show only diff.ago.hour.  translation is not included by default 
translator:      { fallbacks: ["%locale%"] } is activated
Symfony 3.1

**Comment by NiR-** [comment]
Which locale and fallback do you use?

**Comment by Einenlum** [comment]
Too few details about the problem. I close this issue for now. Feel free to reopen it if you have more details about it.

**Comment by etshy** [comment]
I think I have the same problem.

When I have the following configuration
```
framework:
    default_locale: 'fr'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks: ['fr']
```

The filter shows "diff.ago.hour"
https://puu.sh/AqgoS/97265fee90.png

If I change my translator config for this
```
framework:
    default_locale: 'fr'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks: ['en']
```
It works but show in french : https://puu.sh/AqgqF/acd55548a0.png

If I change the default local to 'en' it show in english.

Seems there is a problem with the `fallbacks` option.
